name: Actualizar No-IP

on:
  workflow_dispatch: # Botón para ejecutar manualmente

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run No-IP Update Script
        env:
          # Aquí conectamos tus Secrets existentes con las variables del script
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_HOSTS: ${{ secrets.NOIP_HOSTS }}
        run: python noip_renew.py
